@startuml P
hide enum empty member
hide metaclass empty member

metaclass ABC

enum Stat
enum PokemonType
enum Nature
enum TargetCategory
enum BattleState
enum BattleMode

abstract class BattleAction extends ABC {
    + {abstract} get_id() : String
    + {abstract} get_priority() : int
}
class SwitchAction extends BattleAction {
    - Pokemon switch_in
    - Pokemon switch_out
    
    + get_id() : String
    + get_priority() : int
    + get_switch_in() : Pokemon
    + get_switch_out() : Pokemon
}
class UseItemAction extends BattleAction {
    - Pokemon target
    - Item item
    
    + get_id() : String
    + get_priority() : int
    + get_target() : Pokemon
    + get_item() : Item
}
class PokemonUseMoveAction extends BattleAction {
    - Pokemon user
    - ArrayList<Pokemon> target
    - PokemonMove move
    
    + get_id() : String
    + get_priority() : int
    + get_user() : Pokemon
    + get_target() : ArrayList<Pokemon>
    + get_move() : PokemonMove
}

abstract class BattleFieldProperty extends ABC {
    - String id
    - BattleField BattleField

    + get_id() : String
    + {abstract} apply() : void
}

abstract class PokemonAbility extends ABC {
    - String id
    - Pokemon owner

    + {abstract} run_ability(BattleState, BattleField) : void 
}

abstract class PokemonMoveEffect extends ABC {
    - String id

    + get_id() : String
    + get_target_category() : TargetCategory
    + set_id(String) : void
    + set_target_category(TargetCategory) : void

    + {abstract} clone() : void
    + {abstract} RunEffect() : void
}

abstract class Item {
    + {abstract} get_category() : String
    + {abstract} use(Pokemon) : void
}

class StatChange {
    - Pokemon wrappee
    - int notch
}

abstract class Status{}

class PokemonMove {
    - String Name
    - String Description
    
    - int Power
    - int Accuracy
    - int MaxPP
    - int PP
    - int Priority

    + getName() : String
    + getDescription() : String
    + getType() : PokemonType
    + getPower() : int
    + getAccuracy() : int
    + getMaxPP() : int
    + getPP() : int
    + getPriority() : int
    + getTargetCategory() : TargetCategory
    + getEffect() : PokemonMoveEffect

    + setName(String) : void
    + setDescription(String) : void
    + setType(PokemonType) : void
    + setPower(int) : void
    + setAccuracy(int) : void
    + setMaxPP(int) : void
    + setPP(int) : void
    + setPriority(int) : void
    + setTargetCategory(TargetCategory) : void
    + setEffect(PokemonMoveEffect) : void
}

class BattleField {
    - ArrayList<BattleFieldProperty> properties
    - BattleMode battle_mode
    - ArrayList<Pokemon> side1
    - ArrayList<Pokemon> side2

    - get_side_bound() : int
    + get_properties() : ArrayList<BattleFieldProperties>
    + get_property_ids() : ArrayList<String>
    + get_side(int) : ArrayList<Pokemon>
    + get_side_id_from_pokemon(String) : int

    + add_property(BattleFieldProperty) : void
    + remove_property(BattleFieldProperty) : void
    + clean_property() : void
    + add_pokemon_to_side(int, Pokemon) : void
    + remove_pokemon_from_side(int, Pokemon) : void

    - run_action(Trainer, BattleAction) : void
    + run_actions() : void
}

class PokemonSpecies {
    - String Name
    
    + get_name() : String
    + get_abilities() : ArrayList<PokemonAbility>
    + get_types() : ArrayList<PokemonType>
    + get_movepool() : ArrayList<Pair<String, PokemonMove>>

    + set_name(String) : void
    + set_abilities(ArrayList<PokemonAbility>) : void
    + set_types(ArrayList<PokemonType>) : void
    + set_movepool(ArrayList<Pair<String, PokemonMove>>) : void
}
class Pokemon extends PokemonSpecies {
    - String Nickname
    - int Level

    - int MaxHP
    - int HP

    - int BaseAtk
    - int Atk
    - int BaseDef
    - int Def
    - int BaseSpA
    - int SpA
    - int BaseSpD
    - int SpD
    - int BaseSpe
    - int Spe

    + get_species() : PokemonSpecies
    + get_nickname() : String
    + get_level() : int
    + get_max_hp() : int
    + get_hp() : int
    + get_base_atk() : int
    + get_base_def() : int
    + get_base_spa() : int
    + get_base_spd() : int
    + get_base_spe() : int
    + get_atk() : int
    + get_def() : int
    + get_spa() : int
    + get_spd() : int
    + get_spe() : int
    + get_acc() : int
    + get_eva() : int
    + get_ability() : PokemonAbility
    + get_nature() : Nature
    + get_moveset() : ArrayList<PokemonMove>
    + get_item() : Item
    
    + set_species(PokemonSpecies) : void
    + set_nickname(String) : void
    + set_level(int) : void
    + set_max_hp() : void
    + set_hp() : void
    + set_base_atk() : void
    + set_base_def() : void
    + set_base_spa() : void
    + set_base_spd() : void
    + set_base_spe() : void
    + set_ability(PokemonAbility) : void
    + set_nature(Nature) : void
    + set_moveset(ArrayList<PokemonMove>) : void
    + set_item(Item) : void
}

abstract class Trainer extends ABC {
    - String Name
    - ArrayList<Pokemon> Team
    - ArrayList<Item> Items
    - BattleAction CurrentAction

    + get_name() : String
    + get_team() : ArrayList<Pokemon>
    + get_item() : ArrayList<Item>
    + get_current_action() : BattleAction

    + use_item(Item, Pokemon) : void
    + has_lost() : boolean
    + {abstract} choose_action() : void
}
class PlayerTrainer extends Trainer {
    + choose_action() : void
}
class AITrainer extends Trainer {
    + choose_action() : void
}

class Music {}

class PokemonBattle {
    - int CurrentTurnID
    - BattleState CurrentState
    - ArrayList<Trainer> team1
    - ArrayList<Trainer> team2

    - handle_turn() : BattleState
    + run_battle() : int
}

PokemonSpecies "0..*" -- "1..*" PokemonMove
PokemonSpecies -- "1..2" PokemonType
PokemonSpecies -- "1..3" PokemonAbility
Pokemon "1" -- "0..1" Item
Pokemon "0..*" -- "1..4" PokemonMove
Pokemon -- "1" Nature
Pokemon -- "1" PokemonAbility
Pokemon <|-- StatChange
Pokemon <|-- Status

StatChange -- "1" Stat
Nature -- "2" Stat

PokemonType "1" -- PokemonMove
PokemonMoveEffect "0..1" -- "1..*" PokemonMove
PokemonMoveEffect -- "1" TargetCategory
PokemonBattle --* BattleField
Pokemon <-- BattleField
BattleFieldProperty <-- BattleField

Trainer "1" -- "1..6" Pokemon
Trainer "2..6" -- "1" PokemonBattle
Trainer "1" -- "0..*" Item
Trainer "0..*" -- "1" BattleAction

PokemonBattle -- Music
PokemonBattle -- "1" BattleState
PokemonBattle -- "1" BattleMode

note "For Abstract Classes in Python" as N1
N1 .. ABC

@enduml